


import businesslogo from "../Assets/business-logo.png"

const Businessdetailsdata  = [
    {
        id: 1,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254716435830",
        open: false,
    },
    {
        id: 2,
        category: "Banks",
        logo:{
            url: businesslogo
        },
        name: "Standard Chartered Bank Kenya Ltd ",
        generalinfo: "About Us We were the first foreign bank in Kenya and have been here for over 100 years. Today, we are one of the leading Banks In Kenya with an excellent franchise of 40 branches spread across the country, 98 automated teller machines (ATMs), 1 Electronic Banking Unit and 1,698 employees. Standard Chartered Bank Kenya Limited was established in 1911 with the first branch opened in Mombasa Treasury Square",
        Address: " Taj Towers, Gr Flr, Upper Hill Rd, Nairobi P.O.Box: 30003 - 00100 Nairobi GPO",
        products: {
            product1: "Personal Unsecured Loans",
            product2: "Auto Loans ",
            product3: " Home Solution Cash",
            product3: " Credit Cards",
            product3: "Visa",
            product4: "Cheques",
            product5: "TT",
            product5: "EFT",
            product5: "RTGS",
        },
        brands: "Brands Stanchart",
        activity: "Banks",
        services: {
            service1: "Investments",
            service2: "Credit Cards",
            service3: "Priority Banking",
            service4: "Saadiq",
            service5: "Loan and mortgages",
            service6: "Personal Banking",
            service7: "Accounts",
        },
        OpeningHours: "Monday - Saturday 8.00am - 5.00pm",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 3,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 4,
        category: "Banks",
        logo:{
            url: businesslogo
        },
        name: "Absa Bank",
        generalinfo: "About Us We were the first foreign bank in Kenya and have been here for over 100 years. Today, we are one of the leading Banks In Kenya with an excellent franchise of 40 branches spread across the country, 98 automated teller machines (ATMs), 1 Electronic Banking Unit and 1,698 employees. Standard Chartered Bank Kenya Limited was established in 1911 with the first branch opened in Mombasa Treasury Square",
        Address: " Taj Towers, Gr Flr, Upper Hill Rd, Nairobi P.O.Box: 30003 - 00100 Nairobi GPO",
        products: {
            product1: "Personal Unsecured Loans",
            product2: "Auto Loans ",
            product3: " Home Solution Cash",
            product3: " Credit Cards",
            product3: "Visa",
            product4: "Cheques",
            product5: "TT",
            product5: "EFT",
            product5: "RTGS",
        },
        brands: "Brands Stanchart",
        activity: "Banks",
        services: {
            service1: "Investments",
            service2: "Credit Cards",
            service3: "Priority Banking",
            service4: "Saadiq",
            service5: "Loan and mortgages",
            service6: "Personal Banking",
            service7: "Accounts",
        },
        OpeningHours: "Monday - Saturday 8.00am - 5.00pm",
        isverified: false,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,

    },
    {
        id: 5,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 6,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: false,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 7,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 8,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 9,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: false,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 10,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 11,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: false,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 12,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 13,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 14,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 15,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: false,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 16,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 17,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: false,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 18,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 19,
        category: "Hotels",
        logo:{
            url: businesslogo
        },
        name: "Sarova Whitesands Beach Resort & SPA Diani ",
        generalinfo: "Situated in the most convenient locations but represent the very pinnacle of luxuriously appointed accommodation in the East African region.",
        Address: " Sarova Whitesands Beach Resort & Spa Premises, Mombasa/Malindi Rd, Mombasa P.O.Box: 90173 - 80100 Mombasa",
        products: {
            product1: "ACCOMMODATION AND CONFERENCE FACILITIES"
        },
        brands: "SAROVA WHITESANDS BEACH RESORT",
        activity: "Hotels",
        OpeningHours: "ALWAYS OPEN",
        isverified: false,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 20,
        category: "Banks",
        logo:{
            url: businesslogo
        },
        name: "Absa Bank",
        generalinfo: "About Us We were the first foreign bank in Kenya and have been here for over 100 years. Today, we are one of the leading Banks In Kenya with an excellent franchise of 40 branches spread across the country, 98 automated teller machines (ATMs), 1 Electronic Banking Unit and 1,698 employees. Standard Chartered Bank Kenya Limited was established in 1911 with the first branch opened in Mombasa Treasury Square",
        Address: " Taj Towers, Gr Flr, Upper Hill Rd, Nairobi P.O.Box: 30003 - 00100 Nairobi GPO",
        products: {
            product1: "Personal Unsecured Loans",
            product2: "Auto Loans ",
            product3: " Home Solution Cash",
            product3: " Credit Cards",
            product3: "Visa",
            product4: "Cheques",
            product5: "TT",
            product5: "EFT",
            product5: "RTGS",
        },
        brands: "Brands Stanchart",
        activity: "Banks",
        services: {
            service1: "Investments",
            service2: "Credit Cards",
            service3: "Priority Banking",
            service4: "Saadiq",
            service5: "Loan and mortgages",
            service6: "Personal Banking",
            service7: "Accounts",
        },
        OpeningHours: "Monday - Saturday 8.00am - 5.00pm",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 21,
        category: "Banks",
        logo:{
            url: businesslogo
        },
        name: "Absa Bank",
        generalinfo: "About Us We were the first foreign bank in Kenya and have been here for over 100 years. Today, we are one of the leading Banks In Kenya with an excellent franchise of 40 branches spread across the country, 98 automated teller machines (ATMs), 1 Electronic Banking Unit and 1,698 employees. Standard Chartered Bank Kenya Limited was established in 1911 with the first branch opened in Mombasa Treasury Square",
        Address: " Taj Towers, Gr Flr, Upper Hill Rd, Nairobi P.O.Box: 30003 - 00100 Nairobi GPO",
        products: {
            product1: "Personal Unsecured Loans",
            product2: "Auto Loans ",
            product3: " Home Solution Cash",
            product3: " Credit Cards",
            product3: "Visa",
            product4: "Cheques",
            product5: "TT",
            product5: "EFT",
            product5: "RTGS",
        },
        brands: "Brands Stanchart",
        activity: "Banks",
        services: {
            service1: "Investments",
            service2: "Credit Cards",
            service3: "Priority Banking",
            service4: "Saadiq",
            service5: "Loan and mortgages",
            service6: "Personal Banking",
            service7: "Accounts",
        },
        OpeningHours: "Monday - Saturday 8.00am - 5.00pm",
        isverified: false,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 22,
        category: "Banks",
        logo:{
            url: businesslogo
        },
        name: "Absa Bank",
        generalinfo: "About Us We were the first foreign bank in Kenya and have been here for over 100 years. Today, we are one of the leading Banks In Kenya with an excellent franchise of 40 branches spread across the country, 98 automated teller machines (ATMs), 1 Electronic Banking Unit and 1,698 employees. Standard Chartered Bank Kenya Limited was established in 1911 with the first branch opened in Mombasa Treasury Square",
        Address: " Taj Towers, Gr Flr, Upper Hill Rd, Nairobi P.O.Box: 30003 - 00100 Nairobi GPO",
        products: {
            product1: "Personal Unsecured Loans",
            product2: "Auto Loans ",
            product3: " Home Solution Cash",
            product3: " Credit Cards",
            product3: "Visa",
            product4: "Cheques",
            product5: "TT",
            product5: "EFT",
            product5: "RTGS",
        },
        brands: "Brands Stanchart",
        activity: "Banks",
        services: {
            service1: "Investments",
            service2: "Credit Cards",
            service3: "Priority Banking",
            service4: "Saadiq",
            service5: "Loan and mortgages",
            service6: "Personal Banking",
            service7: "Accounts",
        },
        OpeningHours: "Monday - Saturday 8.00am - 5.00pm",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 23,
        category: "Banks",
        logo:{
            url: businesslogo
        },
        name: "Absa Bank",
        generalinfo: "About Us We were the first foreign bank in Kenya and have been here for over 100 years. Today, we are one of the leading Banks In Kenya with an excellent franchise of 40 branches spread across the country, 98 automated teller machines (ATMs), 1 Electronic Banking Unit and 1,698 employees. Standard Chartered Bank Kenya Limited was established in 1911 with the first branch opened in Mombasa Treasury Square",
        Address: " Taj Towers, Gr Flr, Upper Hill Rd, Nairobi P.O.Box: 30003 - 00100 Nairobi GPO",
        products: {
            product1: "Personal Unsecured Loans",
            product2: "Auto Loans ",
            product3: " Home Solution Cash",
            product3: " Credit Cards",
            product3: "Visa",
            product4: "Cheques",
            product5: "TT",
            product5: "EFT",
            product5: "RTGS",
        },
        brands: "Brands Stanchart",
        activity: "Banks",
        services: {
            service1: "Investments",
            service2: "Credit Cards",
            service3: "Priority Banking",
            service4: "Saadiq",
            service5: "Loan and mortgages",
            service6: "Personal Banking",
            service7: "Accounts",
        },
        OpeningHours: "Monday - Saturday 8.00am - 5.00pm",
        isverified: false,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 24,
        category: "Banks",
        logo:{
            url: businesslogo
        },
        name: "Absa Bank",
        generalinfo: "About Us We were the first foreign bank in Kenya and have been here for over 100 years. Today, we are one of the leading Banks In Kenya with an excellent franchise of 40 branches spread across the country, 98 automated teller machines (ATMs), 1 Electronic Banking Unit and 1,698 employees. Standard Chartered Bank Kenya Limited was established in 1911 with the first branch opened in Mombasa Treasury Square",
        Address: " Taj Towers, Gr Flr, Upper Hill Rd, Nairobi P.O.Box: 30003 - 00100 Nairobi GPO",
        products: {
            product1: "Personal Unsecured Loans",
            product2: "Auto Loans ",
            product3: " Home Solution Cash",
            product3: " Credit Cards",
            product3: "Visa",
            product4: "Cheques",
            product5: "TT",
            product5: "EFT",
            product5: "RTGS",
        },
        brands: "Brands Stanchart",
        activity: "Banks",
        services: {
            service1: "Investments",
            service2: "Credit Cards",
            service3: "Priority Banking",
            service4: "Saadiq",
            service5: "Loan and mortgages",
            service6: "Personal Banking",
            service7: "Accounts",
        },
        OpeningHours: "Monday - Saturday 8.00am - 5.00pm",
        isverified: false,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 25,
        category: "Banks",
        logo:{
            url: businesslogo
        },
        name: "Absa Bank",
        generalinfo: "About Us We were the first foreign bank in Kenya and have been here for over 100 years. Today, we are one of the leading Banks In Kenya with an excellent franchise of 40 branches spread across the country, 98 automated teller machines (ATMs), 1 Electronic Banking Unit and 1,698 employees. Standard Chartered Bank Kenya Limited was established in 1911 with the first branch opened in Mombasa Treasury Square",
        Address: " Taj Towers, Gr Flr, Upper Hill Rd, Nairobi P.O.Box: 30003 - 00100 Nairobi GPO",
        products: {
            product1: "Personal Unsecured Loans",
            product2: "Auto Loans ",
            product3: " Home Solution Cash",
            product3: " Credit Cards",
            product3: "Visa",
            product4: "Cheques",
            product5: "TT",
            product5: "EFT",
            product5: "RTGS",
        },
        brands: "Brands Stanchart",
        activity: "Banks",
        services: {
            service1: "Investments",
            service2: "Credit Cards",
            service3: "Priority Banking",
            service4: "Saadiq",
            service5: "Loan and mortgages",
            service6: "Personal Banking",
            service7: "Accounts",
        },
        OpeningHours: "Monday - Saturday 8.00am - 5.00pm",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 26,
        category: "Banks",
        logo:{
            url: businesslogo
        },
        name: "Absa Bank",
        generalinfo: "About Us We were the first foreign bank in Kenya and have been here for over 100 years. Today, we are one of the leading Banks In Kenya with an excellent franchise of 40 branches spread across the country, 98 automated teller machines (ATMs), 1 Electronic Banking Unit and 1,698 employees. Standard Chartered Bank Kenya Limited was established in 1911 with the first branch opened in Mombasa Treasury Square",
        Address: " Taj Towers, Gr Flr, Upper Hill Rd, Nairobi P.O.Box: 30003 - 00100 Nairobi GPO",
        products: {
            product1: "Personal Unsecured Loans",
            product2: "Auto Loans ",
            product3: " Home Solution Cash",
            product3: " Credit Cards",
            product3: "Visa",
            product4: "Cheques",
            product5: "TT",
            product5: "EFT",
            product5: "RTGS",
        },
        brands: "Brands Stanchart",
        activity: "Banks",
        services: {
            service1: "Investments",
            service2: "Credit Cards",
            service3: "Priority Banking",
            service4: "Saadiq",
            service5: "Loan and mortgages",
            service6: "Personal Banking",
            service7: "Accounts",
        },
        OpeningHours: "Monday - Saturday 8.00am - 5.00pm",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 27,
        category: "Banks",
        logo:{
            url: businesslogo
        },
        name: "Absa Bank",
        generalinfo: "About Us We were the first foreign bank in Kenya and have been here for over 100 years. Today, we are one of the leading Banks In Kenya with an excellent franchise of 40 branches spread across the country, 98 automated teller machines (ATMs), 1 Electronic Banking Unit and 1,698 employees. Standard Chartered Bank Kenya Limited was established in 1911 with the first branch opened in Mombasa Treasury Square",
        Address: " Taj Towers, Gr Flr, Upper Hill Rd, Nairobi P.O.Box: 30003 - 00100 Nairobi GPO",
        products: {
            product1: "Personal Unsecured Loans",
            product2: "Auto Loans ",
            product3: " Home Solution Cash",
            product3: " Credit Cards",
            product3: "Visa",
            product4: "Cheques",
            product5: "TT",
            product5: "EFT",
            product5: "RTGS",
        },
        brands: "Brands Stanchart",
        activity: "Banks",
        services: {
            service1: "Investments",
            service2: "Credit Cards",
            service3: "Priority Banking",
            service4: "Saadiq",
            service5: "Loan and mortgages",
            service6: "Personal Banking",
            service7: "Accounts",
        },
        OpeningHours: "Monday - Saturday 8.00am - 5.00pm",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: true,
    },
    {
        id: 28,
        category: "Banks",
        logo:{
            url: businesslogo
        },
        name: "Absa Bank",
        generalinfo: "About Us We were the first foreign bank in Kenya and have been here for over 100 years. Today, we are one of the leading Banks In Kenya with an excellent franchise of 40 branches spread across the country, 98 automated teller machines (ATMs), 1 Electronic Banking Unit and 1,698 employees. Standard Chartered Bank Kenya Limited was established in 1911 with the first branch opened in Mombasa Treasury Square",
        Address: " Taj Towers, Gr Flr, Upper Hill Rd, Nairobi P.O.Box: 30003 - 00100 Nairobi GPO",
        products: {
            product1: "Personal Unsecured Loans",
            product2: "Auto Loans ",
            product3: " Home Solution Cash",
            product3: " Credit Cards",
            product3: "Visa",
            product4: "Cheques",
            product5: "TT",
            product5: "EFT",
            product5: "RTGS",
        },
        brands: "Brands Stanchart",
        activity: "Banks",
        services: {
            service1: "Investments",
            service2: "Credit Cards",
            service3: "Priority Banking",
            service4: "Saadiq",
            service5: "Loan and mortgages",
            service6: "Personal Banking",
            service7: "Accounts",
        },
        OpeningHours: "Monday - Saturday 8.00am - 5.00pm",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
         open: false,
    },
    {
        id: 29,
        category: "Banks",
        logo:{
            url: businesslogo
        },
        name: "Absa Bank",
        generalinfo: "About Us We were the first foreign bank in Kenya and have been here for over 100 years. Today, we are one of the leading Banks In Kenya with an excellent franchise of 40 branches spread across the country, 98 automated teller machines (ATMs), 1 Electronic Banking Unit and 1,698 employees. Standard Chartered Bank Kenya Limited was established in 1911 with the first branch opened in Mombasa Treasury Square",
        Address: " Taj Towers, Gr Flr, Upper Hill Rd, Nairobi P.O.Box: 30003 - 00100 Nairobi GPO",
        products: {
            product1: "Personal Unsecured Loans",
            product2: "Auto Loans ",
            product3: " Home Solution Cash",
            product3: " Credit Cards",
            product3: "Visa",
            product4: "Cheques",
            product5: "TT",
            product5: "EFT",
            product5: "RTGS",
        },
        brands: "Brands Stanchart",
        activity: "Banks",
        services: {
            service1: "Investments",
            service2: "Credit Cards",
            service3: "Priority Banking",
            service4: "Saadiq",
            service5: "Loan and mortgages",
            service6: "Personal Banking",
            service7: "Accounts",
        },
        OpeningHours: "Monday - Saturday 8.00am - 5.00pm",
        isverified: true,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
         open: false,
    },
    {
        id: 30,
        category: "Banks",
        logo:{
            url: businesslogo
        },
        name: "Absa Bank",
        generalinfo: "About Us We were the first foreign bank in Kenya and have been here for over 100 years. Today, we are one of the leading Banks In Kenya with an excellent franchise of 40 branches spread across the country, 98 automated teller machines (ATMs), 1 Electronic Banking Unit and 1,698 employees. Standard Chartered Bank Kenya Limited was established in 1911 with the first branch opened in Mombasa Treasury Square",
        Address: " Taj Towers, Gr Flr, Upper Hill Rd, Nairobi P.O.Box: 30003 - 00100 Nairobi GPO",
        products: {
            product1: "Personal Unsecured Loans",
            product2: "Auto Loans ",
            product3: " Home Solution Cash",
            product3: " Credit Cards",
            product3: "Visa",
            product4: "Cheques",
            product5: "TT",
            product5: "EFT",
            product5: "RTGS",
        },
        brands: "Brands Stanchart",
        activity: "Banks",
        services: {
            service1: "Investments",
            service2: "Credit Cards",
            service3: "Priority Banking",
            service4: "Saadiq",
            service5: "Loan and mortgages",
            service6: "Personal Banking",
            service7: "Accounts",
        },
        OpeningHours: "Monday - Saturday 8.00am - 5.00pm",
        isverified: false,
        phonenumber: "+254 716 435 830",
        email: "info@yellowpageskenya",
        whatsapp: "+254 716 435 830",
        open: false,
    },
]

export default Businessdetailsdata;